### ISSUE TITLE
build images for different architectures

### ISSUE THREAD

**Issue by w0rng** [amnezia-vpn/amneziawg-go#36]
Maybe add an image build for different architectures to ci/cd?  
For example, like this:

```yaml
 - name: Build
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
          tags: ${{ steps.metadata.outputs.tags }}
```
